# Generated by Django 4.0.6 on 2022-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0022_comentario_comentario1_comentario_comentario2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='cartao',
        ),
        migrations.AddField(
            model_name='cartao',
            name='cartao1',
            field=models.ManyToManyField(to='pjgplantas.usuario'),
        ),
    ]
