# Generated by Django 4.0.6 on 2022-09-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0023_remove_cartao_cartao_cartao_cartao1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='planta',
        ),
        migrations.AddField(
            model_name='itenscarrinho',
            name='planta',
            field=models.ManyToManyField(to='pjgplantas.planta'),
        ),
    ]
