# Generated by Django 4.0.6 on 2022-09-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0025_remove_planta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='cartao1',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
