# Generated by Django 4.0.6 on 2022-09-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0026_remove_cartao_cartao1_remove_comentario_comentario1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
