# Generated by Django 4.1.1 on 2022-10-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0030_alter_comentario_texto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Midia",
        ),
    ]
