# Generated by Django 4.1.2 on 2022-10-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0032_planta_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="planta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="pjgplantas.planta",
            ),
            preserve_default=False,
        ),
    ]
