# Generated by Django 4.1.2 on 2022-10-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0033_comentario_planta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="comentario2",
            new_name="usuario",
        ),
    ]
