# Generated by Django 4.1.2 on 2022-10-06 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0034_rename_comentario2_comentario_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="dth",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
