# Generated by Django 4.1.2 on 2022-10-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0035_alter_comentario_dth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="planta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comentarios",
                to="pjgplantas.planta",
            ),
        ),
    ]
