# Generated by Django 4.1.2 on 2022-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0036_alter_comentario_planta"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidocarrinho",
            name="complemento",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedidocarrinho",
            name="cpf",
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedidocarrinho",
            name="endereco",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedidocarrinho",
            name="rg",
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
