# Generated by Django 4.1.2 on 2022-10-20 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pjgplantas", "0037_pedidocarrinho_complemento_pedidocarrinho_cpf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedidocarrinho",
            name="quantidade_itens",
        ),
        migrations.AddField(
            model_name="pedidocarrinho",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pix",
            name="cnpj",
            field=models.CharField(max_length=18),
        ),
    ]
