# Generated by Django 4.1.2 on 2022-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0040_cartao_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartao",
            name="validade",
            field=models.CharField(max_length=5),
        ),
    ]
