# Generated by Django 4.1.2 on 2022-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0041_alter_cartao_validade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartao",
            name="cvv",
            field=models.CharField(max_length=3),
        ),
    ]
