# Generated by Django 4.1.2 on 2022-10-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0043_remove_itenscarrinho_pedido_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedidocarrinho",
            old_name="itencarrinho",
            new_name="itenscarrinho",
        ),
    ]
