# Generated by Django 4.1.2 on 2022-10-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0046_remove_itenscarrinho_qnt_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscarrinho",
            name="qnt",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
