# Generated by Django 4.1.2 on 2022-10-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0047_itenscarrinho_qnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itenscarrinho",
            name="qnt",
        ),
        migrations.AlterField(
            model_name="pedidocarrinho",
            name="itenscarrinho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens",
                to="pjgplantas.itenscarrinho",
            ),
        ),
    ]
