# Generated by Django 4.1.2 on 2022-10-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0050_compra_itenscompra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="status",
        ),
    ]
