# Generated by Django 4.1.2 on 2022-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0051_remove_compra_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="cpf",
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
