# Generated by Django 4.1.2 on 2022-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0052_compra_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="complemento",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compra",
            name="endereco",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compra",
            name="rg",
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
