# Generated by Django 4.1.2 on 2022-10-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0055_rename_pix_pedidocarrinho_pix1"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="cartao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pjgplantas.cartao",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="pix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pjgplantas.pix",
            ),
        ),
    ]
