# Generated by Django 4.1.2 on 2022-10-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0056_compra_cartao_compra_pix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedidocarrinho",
            name="itenscarrinho",
        ),
    ]
