# Generated by Django 4.1.2 on 2022-10-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0060_remove_pedidocarrinho_boleto1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedidocarrinho",
            name="complemento",
        ),
        migrations.RemoveField(
            model_name="pedidocarrinho",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="pedidocarrinho",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="pedidocarrinho",
            name="rg",
        ),
    ]
