# Generated by Django 4.1.2 on 2022-10-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0061_remove_pedidocarrinho_complemento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itenscarrinho",
            name="usuario",
        ),
    ]
