# Generated by Django 4.1.2 on 2022-11-16 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0065_delete_itenscarrinho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="planta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="pjgplantas.planta",
            ),
        ),
    ]
