# Generated by Django 4.1.2 on 2022-11-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0066_alter_itenscompra_planta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="planta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="pjgplantas.planta",
            ),
        ),
    ]
