# Generated by Django 4.1.2 on 2022-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0067_alter_comentario_planta"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscompra",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
