# Generated by Django 4.1.2 on 2022-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pjgplantas", "0068_itenscompra_valor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itenscompra",
            name="valor",
        ),
        migrations.AlterField(
            model_name="compra",
            name="complemento",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="cpf",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="endereco",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="rg",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
